import '../models/country_model.dart';

List<CountryModel> countries = [
  const CountryModel(name: 'Afghanistan', countryCode: 'AF'),
  const CountryModel(name: 'Albania', countryCode: 'AL'),
  const CountryModel(name: 'Algeria', countryCode: 'DZ'),
  const CountryModel(name: 'Andorra', countryCode: 'AD'),
  const CountryModel(name: 'Angola', countryCode: 'AO'),
  const CountryModel(name: 'Antigua and Barbuda', countryCode: 'AG'),
  const CountryModel(name: 'Argentina', countryCode: 'AR'),
  const CountryModel(name: 'Armenia', countryCode: 'AM'),
  const CountryModel(name: 'Australia', countryCode: 'AU'),
  const CountryModel(name: 'Austria', countryCode: 'AT'),
  const CountryModel(name: 'Azerbaijan', countryCode: 'AZ'),
  const CountryModel(name: 'Bahamas', countryCode: 'BS'),
  const CountryModel(name: 'Bahrain', countryCode: 'BH'),
  const CountryModel(name: 'Bangladesh', countryCode: 'BD'),
  const CountryModel(name: 'Barbados', countryCode: 'BB'),
  const CountryModel(name: 'Belarus', countryCode: 'BY'),
  const CountryModel(name: 'Belgium', countryCode: 'BE'),
  const CountryModel(name: 'Belize', countryCode: 'BZ'),
  const CountryModel(name: 'Benin', countryCode: 'BJ'),
  const CountryModel(name: 'Bhutan', countryCode: 'BT'),
  const CountryModel(name: 'Bolivia', countryCode: 'BO'),
  const CountryModel(name: 'Bosnia and Herzegovina', countryCode: 'BA'),
  const CountryModel(name: 'Botswana', countryCode: 'BW'),
  const CountryModel(name: 'Brazil', countryCode: 'BR'),
  const CountryModel(name: 'Brunei', countryCode: 'BN'),
  const CountryModel(name: 'Bulgaria', countryCode: 'BG'),
  const CountryModel(name: 'Burkina Faso', countryCode: 'BF'),
  const CountryModel(name: 'Burundi', countryCode: 'BI'),
  const CountryModel(name: 'Cabo Verde', countryCode: 'CV'),
  const CountryModel(name: 'Cambodia', countryCode: 'KH'),
  const CountryModel(name: 'Cameroon', countryCode: 'CM'),
  const CountryModel(name: 'Canada', countryCode: 'CA'),
  const CountryModel(name: 'Central African Republic', countryCode: 'CF'),
  const CountryModel(name: 'Chad', countryCode: 'TD'),
  const CountryModel(name: 'Chile', countryCode: 'CL'),
  const CountryModel(name: 'China', countryCode: 'CN'),
  const CountryModel(name: 'Colombia', countryCode: 'CO'),
  const CountryModel(name: 'Comoros', countryCode: 'KM'),
  const CountryModel(name: 'Congo', countryCode: 'CG'),
  const CountryModel(name: 'Costa Rica', countryCode: 'CR'),
  const CountryModel(name: 'Croatia', countryCode: 'HR'),
  const CountryModel(name: 'Cuba', countryCode: 'CU'),
  const CountryModel(name: 'Cyprus', countryCode: 'CY'),
  const CountryModel(name: 'Czechia', countryCode: 'CZ'),
  const CountryModel(name: 'Denmark', countryCode: 'DK'),
  const CountryModel(name: 'Djibouti', countryCode: 'DJ'),
  const CountryModel(name: 'Dominica', countryCode: 'DM'),
  const CountryModel(name: 'Dominican Republic', countryCode: 'DO'),
  const CountryModel(name: 'Ecuador', countryCode: 'EC'),
  const CountryModel(name: 'Egypt', countryCode: 'EG'),
  const CountryModel(name: 'El Salvador', countryCode: 'SV'),
  const CountryModel(name: 'Equatorial Guinea', countryCode: 'GQ'),
  const CountryModel(name: 'Eritrea', countryCode: 'ER'),
  const CountryModel(name: 'Estonia', countryCode: 'EE'),
  const CountryModel(name: 'Eswatini', countryCode: 'SZ'),
  const CountryModel(name: 'Ethiopia', countryCode: 'ET'),
  const CountryModel(name: 'Fiji', countryCode: 'FJ'),
  const CountryModel(name: 'Finland', countryCode: 'FI'),
  const CountryModel(name: 'France', countryCode: 'FR'),
  const CountryModel(name: 'Gabon', countryCode: 'GA'),
  const CountryModel(name: 'Gambia', countryCode: 'GM'),
  const CountryModel(name: 'Georgia', countryCode: 'GE'),
  const CountryModel(name: 'Germany', countryCode: 'DE'),
  const CountryModel(name: 'Ghana', countryCode: 'GH'),
  const CountryModel(name: 'Greece', countryCode: 'GR'),
  const CountryModel(name: 'Grenada', countryCode: 'GD'),
  const CountryModel(name: 'Guatemala', countryCode: 'GT'),
  const CountryModel(name: 'Guinea', countryCode: 'GN'),
  const CountryModel(name: 'Guinea-Bissau', countryCode: 'GW'),
  const CountryModel(name: 'Guyana', countryCode: 'GY'),
  const CountryModel(name: 'Haiti', countryCode: 'HT'),
  const CountryModel(name: 'Honduras', countryCode: 'HN'),
  const CountryModel(name: 'Hungary', countryCode: 'HU'),
  const CountryModel(name: 'Iceland', countryCode: 'IS'),
  const CountryModel(name: 'India', countryCode: 'IN'),
  const CountryModel(name: 'Indonesia', countryCode: 'ID'),
  const CountryModel(name: 'Iran', countryCode: 'IR'),
  const CountryModel(name: 'Iraq', countryCode: 'IQ'),
  const CountryModel(name: 'Ireland', countryCode: 'IE'),
  const CountryModel(name: 'Israel', countryCode: 'IL'),
  const CountryModel(name: 'Italy', countryCode: 'IT'),
  const CountryModel(name: 'Jamaica', countryCode: 'JM'),
  const CountryModel(name: 'Japan', countryCode: 'JP'),
  const CountryModel(name: 'Jordan', countryCode: 'JO'),
  const CountryModel(name: 'Kazakhstan', countryCode: 'KZ'),
  const CountryModel(name: 'Kenya', countryCode: 'KE'),
  const CountryModel(name: 'Kiribati', countryCode: 'KI'),
  const CountryModel(name: 'Korea, North', countryCode: 'KP'),
  const CountryModel(name: 'Korea, South', countryCode: 'KR'),
  const CountryModel(name: 'Kosovo', countryCode: 'XK'),
  const CountryModel(name: 'Kuwait', countryCode: 'KW'),
  const CountryModel(name: 'Kyrgyzstan', countryCode: 'KG'),
  const CountryModel(name: 'Laos', countryCode: 'LA'),
  const CountryModel(name: 'Latvia', countryCode: 'LV'),
  const CountryModel(name: 'Lebanon', countryCode: 'LB'),
  const CountryModel(name: 'Lesotho', countryCode: 'LS'),
  const CountryModel(name: 'Liberia', countryCode: 'LR'),
  const CountryModel(name: 'Libya', countryCode: 'LY'),
  const CountryModel(name: 'Liechtenstein', countryCode: 'LI'),
  const CountryModel(name: 'Lithuania', countryCode: 'LT'),
  const CountryModel(name: 'Luxembourg', countryCode: 'LU'),
  const CountryModel(name: 'Madagascar', countryCode: 'MG'),
  const CountryModel(name: 'Malawi', countryCode: 'MW'),
  const CountryModel(name: 'Malaysia', countryCode: 'MY'),
  const CountryModel(name: 'Maldives', countryCode: 'MV'),
  const CountryModel(name: 'Mali', countryCode: 'ML'),
  const CountryModel(name: 'Malta', countryCode: 'MT'),
  const CountryModel(name: 'Marshall Islands', countryCode: 'MH'),
  const CountryModel(name: 'Mauritania', countryCode: 'MR'),
  const CountryModel(name: 'Mauritius', countryCode: 'MU'),
  const CountryModel(name: 'Mexico', countryCode: 'MX'),
  const CountryModel(name: 'Micronesia', countryCode: 'FM'),
  const CountryModel(name: 'Moldova', countryCode: 'MD'),
  const CountryModel(name: 'Monaco', countryCode: 'MC'),
  const CountryModel(name: 'Mongolia', countryCode: 'MN'),
  const CountryModel(name: 'Montenegro', countryCode: 'ME'),
  const CountryModel(name: 'Morocco', countryCode: 'MA'),
  const CountryModel(name: 'Mozambique', countryCode: 'MZ'),
  const CountryModel(name: 'Myanmar', countryCode: 'MM'),
  const CountryModel(name: 'Namibia', countryCode: 'NA'),
  const CountryModel(name: 'Nauru', countryCode: 'NR'),
  const CountryModel(name: 'Nepal', countryCode: 'NP'),
  const CountryModel(name: 'Netherlands', countryCode: 'NL'),
  const CountryModel(name: 'New Zealand', countryCode: 'NZ'),
  const CountryModel(name: 'Nicaragua', countryCode: 'NI'),
  const CountryModel(name: 'Niger', countryCode: 'NE'),
  const CountryModel(name: 'Nigeria', countryCode: 'NG'),
  const CountryModel(name: 'North Macedonia', countryCode: 'MK'),
  const CountryModel(name: 'Norway', countryCode: 'NO'),
  const CountryModel(name: 'Oman', countryCode: 'OM'),
  const CountryModel(name: 'Pakistan', countryCode: 'PK'),
  const CountryModel(name: 'Palau', countryCode: 'PW'),
  const CountryModel(name: 'Panama', countryCode: 'PA'),
  const CountryModel(name: 'Papua New Guinea', countryCode: 'PG'),
  const CountryModel(name: 'Paraguay', countryCode: 'PY'),
  const CountryModel(name: 'Peru', countryCode: 'PE'),
  const CountryModel(name: 'Philippines', countryCode: 'PH'),
  const CountryModel(name: 'Poland', countryCode: 'PL'),
  const CountryModel(name: 'Portugal', countryCode: 'PT'),
  const CountryModel(name: 'Qatar', countryCode: 'QA'),
  const CountryModel(name: 'Romania', countryCode: 'RO'),
  const CountryModel(name: 'Russia', countryCode: 'RU'),
  const CountryModel(name: 'Rwanda', countryCode: 'RW'),
  const CountryModel(name: 'Saint Kitts and Nevis', countryCode: 'KN'),
  const CountryModel(name: 'Saint Lucia', countryCode: 'LC'),
  const CountryModel(
      name: 'Saint Vincent and the Grenadines', countryCode: 'VC'),
  const CountryModel(name: 'Samoa', countryCode: 'WS'),
  const CountryModel(name: 'San Marino', countryCode: 'SM'),
  const CountryModel(name: 'Sao Tome and Principe', countryCode: 'ST'),
  const CountryModel(name: 'Saudi Arabia', countryCode: 'SA'),
  const CountryModel(name: 'Senegal', countryCode: 'SN'),
  const CountryModel(name: 'Serbia', countryCode: 'RS'),
  const CountryModel(name: 'Seychelles', countryCode: 'SC'),
  const CountryModel(name: 'Sierra Leone', countryCode: 'SL'),
  const CountryModel(name: 'Singapore', countryCode: 'SG'),
  const CountryModel(name: 'Slovakia', countryCode: 'SK'),
  const CountryModel(name: 'Slovenia', countryCode: 'SI'),
  const CountryModel(name: 'Solomon Islands', countryCode: 'SB'),
  const CountryModel(name: 'Somalia', countryCode: 'SO'),
  const CountryModel(name: 'South Africa', countryCode: 'ZA'),
  const CountryModel(name: 'South Sudan', countryCode: 'SS'),
  const CountryModel(name: 'Spain', countryCode: 'ES'),
  const CountryModel(name: 'Sri Lanka', countryCode: 'LK'),
  const CountryModel(name: 'Sudan', countryCode: 'SD'),
  const CountryModel(name: 'Suriname', countryCode: 'SR'),
  const CountryModel(name: 'Sweden', countryCode: 'SE'),
  const CountryModel(name: 'Switzerland', countryCode: 'CH'),
  const CountryModel(name: 'Syria', countryCode: 'SY'),
  const CountryModel(name: 'Taiwan', countryCode: 'TW'),
  const CountryModel(name: 'Tajikistan', countryCode: 'TJ'),
  const CountryModel(name: 'Tanzania', countryCode: 'TZ'),
  const CountryModel(name: 'Thailand', countryCode: 'TH'),
  const CountryModel(name: 'Timor-Leste', countryCode: 'TL'),
  const CountryModel(name: 'Togo', countryCode: 'TG'),
  const CountryModel(name: 'Tonga', countryCode: 'TO'),
  const CountryModel(name: 'Trinidad and Tobago', countryCode: 'TT'),
  const CountryModel(name: 'Tunisia', countryCode: 'TN'),
  const CountryModel(name: 'Turkey', countryCode: 'TR'),
  const CountryModel(name: 'Turkmenistan', countryCode: 'TM'),
  const CountryModel(name: 'Tuvalu', countryCode: 'TV'),
  const CountryModel(name: 'Uganda', countryCode: 'UG'),
  const CountryModel(name: 'Ukraine', countryCode: 'UA'),
  const CountryModel(name: 'United Arab Emirates', countryCode: 'AE'),
  const CountryModel(name: 'United Kingdom', countryCode: 'GB'),
  const CountryModel(name: 'United States', countryCode: 'US'),
  const CountryModel(name: 'Uruguay', countryCode: 'UY'),
  const CountryModel(name: 'Uzbekistan', countryCode: 'UZ'),
  const CountryModel(name: 'Vanuatu', countryCode: 'VU'),
  const CountryModel(name: 'Vatican City', countryCode: 'VA'),
  const CountryModel(name: 'Venezuela', countryCode: 'VE'),
  const CountryModel(name: 'Vietnam', countryCode: 'VN'),
  const CountryModel(name: 'Yemen', countryCode: 'YE'),
  const CountryModel(name: 'Zambia', countryCode: 'ZM'),
  const CountryModel(name: 'Zimbabwe', countryCode: 'ZW'),
];
