import '../models/place_model.dart';

List<PlaceModel> listPlaces = [
  PlaceModel(
    place_id: "1",
    name: "Qingdao Beach",
    address: "123 Coastal Avenue, Qingdao, Shandong",
    latitude: 36.0679,
    longitude: 120.3826,
  ),
  PlaceModel(
    place_id: "2",
    name: "Taishan Mountain",
    address: "456 Mountain Road, Tai'an, Shandong",
    latitude: 36.2553,
    longitude: 117.0944,
  ),
  PlaceModel(
    place_id: "3",
    name: "Confucius Temple",
    address: "789 Temple Street, Qufu, Shandong",
    latitude: 35.5951,
    longitude: 117.0086,
  ),
  PlaceModel(
    place_id: "4",
    name: "Weifang Kite Museum",
    address: "101 Sky High Avenue, Weifang, Shandong",
    latitude: 36.7168,
    longitude: 119.1662,
  ),
  PlaceModel(
    place_id: "5",
    name: "Jinan Springs Park",
    address: "210 Spring Street, Jinan, Shandong",
    latitude: 36.6512,
    longitude: 117.1201,
  ),
  PlaceModel(
    place_id: "6",
    name: "Zoucheng Underground Caves",
    address: "333 Cave Road, Zoucheng, Shandong",
    latitude: 35.4088,
    longitude: 116.9614,
  ),
  PlaceModel(
    place_id: "7",
    name: "Yantai Coastal Walkway",
    address: "444 Seaside Street, Yantai, Shandong",
    latitude: 37.4714,
    longitude: 121.4407,
  ),
  PlaceModel(
    place_id: "8",
    name: "Linyi Ancient City",
    address: "567 Ancient Lane, Linyi, Shandong",
    latitude: 35.0572,
    longitude: 118.3420,
  ),
  PlaceModel(
    place_id: "9",
    name: "Rizhao Golden Beach",
    address: "678 Golden Shore, Rizhao, Shandong",
    latitude: 35.4130,
    longitude: 119.5270,
  ),
  PlaceModel(
    place_id: "10",
    name: "Dengzhou Hot Springs",
    address: "789 Relaxation Road, Dengzhou, Shandong",
    latitude: 37.7855,
    longitude: 120.3714,
  ),
  PlaceModel(
    place_id: "11",
    name: "Dezhou Cultural Museum",
    address: "101 Heritage Street, Dezhou, Shandong",
    latitude: 37.4347,
    longitude: 116.3575,
  ),
  PlaceModel(
    place_id: "12",
    name: "Binzhou Sunflower Fields",
    address: "210 Sunshine Avenue, Binzhou, Shandong",
    latitude: 37.3835,
    longitude: 118.0214,
  ),
  PlaceModel(
    place_id: "13",
    name: "Heze Lotus Pond",
    address: "333 Water Lily Lane, Heze, Shandong",
    latitude: 35.2392,
    longitude: 115.4725,
  ),
  PlaceModel(
    place_id: "14",
    name: "Zibo Ceramic Art Center",
    address: "444 Clay Street, Zibo, Shandong",
    latitude: 36.8148,
    longitude: 118.0559,
  ),
  PlaceModel(
    place_id: "15",
    name: "Jining Ancient Canal",
    address: "567 Navigational Road, Jining, Shandong",
    latitude: 35.4146,
    longitude: 116.5813,
  ),
  PlaceModel(
    place_id: "16",
    name: "Tai'an Pagoda Park",
    address: "678 Pagoda Street, Tai'an, Shandong",
    latitude: 36.2051,
    longitude: 117.0894,
  ),
  PlaceModel(
    place_id: "17",
    name: "Yantai Wine Vineyards",
    address: "789 Vineyard Lane, Yantai, Shandong",
    latitude: 37.4419,
    longitude: 121.2590,
  ),
  PlaceModel(
    place_id: "18",
    name: "Weihai Cliff Walk",
    address: "101 Cliffside Avenue, Weihai, Shandong",
    latitude: 37.5015,
    longitude: 122.1156,
  ),
  PlaceModel(
    place_id: "19",
    name: "Zaozhuang Bamboo Forest",
    address: "210 Bamboo Grove, Zaozhuang, Shandong",
    latitude: 34.8708,
    longitude: 117.5544,
  ),
  PlaceModel(
    place_id: "20",
    name: "Rizhao Seaside Park",
    address: "333 Coastal Promenade, Rizhao, Shandong",
    latitude: 35.4164,
    longitude: 119.5152,
  ),
  PlaceModel(
    place_id: "21",
    name: "Linyi University",
    address: "789 University Avenue, Linyi, Shandong",
    latitude: 35.0526,
    longitude: 118.3421,
    description: "A renowned educational institution in Linyi.",
    type_place: "University",
    phone_number: null,
    website: "https://www.lyu.edu.cn",
  ),
  PlaceModel(
    place_id: "22",
    name: "Linyi Residence",
    address: "456 Home Street, Linyi, Shandong",
    latitude: 35.0470,
    longitude: 118.3425,
    description: "Personal residence in Linyi.",
    type_place: "Home",
    phone_number: null, // Set to null if not available
    website: null, // Set to null if not available
  ),
  PlaceModel(
    place_id: "23",
    name: "Linyi Office",
    address: "789 Office Park, Linyi, Shandong",
    latitude: 35.0455,
    longitude: 118.3368,
    description: "Workplace in Linyi.",
    type_place: "Work",
    phone_number: null, // Set to null if not available
    website: "https://www.companywebsite.com",
  ),
];
